image: registry.gitlab.com/middlingintereset/eventing:latest

before_script:
  - clang -v
  - uname -a

build:
  script:
    - make CC=clang
  artifacts:
    paths: 
      - debug/daemon
      - debug/client
    expire_in: 1 week
      

